stocks/views/stock_routes.py
"""This module contains routes related to stocks in a Flask application."""
from flask import render_template, Blueprint, redirect, request, url_for, flash
import requests
from requests.exceptions import JSONDecodeError

stock_bp = Blueprint('stocks', __name__, url_prefix='/stocks')
BASE_URL = 'http://localhost:5000/api/stocks'
headers = {'Content-Type': 'application/json'}


@stock_bp.route('', methods=['GET'])
def list_stocks():
    """
        Route to get a list of all stocks.
    """
    try:
        response = requests.get(BASE_URL, timeout=5).json()
        return render_template('stocks.html', stocks=response)
    except JSONDecodeError:
        return render_template('stocks.html')


@stock_bp.route('/<int:stock_id>', methods=['GET'])
def get_stock(stock_id: int):
    """
        Route to get a single stock by its ID.
    """
    response = requests.get(BASE_URL + f'/{stock_id}', timeout=5).json()
    return response


@stock_bp.route('', methods=['POST'])
def create_stock():
    """
        Route to create a new stock.
    """
    company = request.form.get('company')
    sector = request.form.get('sector')
    amount = request.form.get('amount')
    price = request.form.get('price')
    data = {'company': company, 'sector': sector, 'amount': amount, 'price': price}
    response = requests.post(BASE_URL, headers=headers, json=data, timeout=5).json()
    if response is False:
        flash('This company is already selling stocks.')
    else:
        flash(f'Company {company} added successfully.', 'success')
    return redirect(url_for('stocks.list_stocks'))


@stock_bp.route('/<int:stock_id>', methods=['GET', 'POST'])
def update_stock(stock_id: int):
    """
        Route to update an existing stock.
    """
    if request.method == 'POST':
        amount = request.form.get('amount')
        price = request.form.get('price')
        data = {'amount': int(amount), 'price': float(price)}
        requests.put(BASE_URL + f'/{stock_id}', headers=headers, json=data, timeout=5).json()
        flash(f'Stock {stock_id} updated successfully.', 'success')
        return redirect(url_for('stocks.list_stocks'))


@stock_bp.route('/<int:stock_id>', methods=['DELETE'])
def delete_stock(stock_id: int):
    """
        Route to delete an existing stock.
    """
    requests.delete(BASE_URL + f'/{stock_id}', timeout=5)
    flash('Stock deleted successfully.', 'success')
    return redirect(url_for('stocks.list_stocks'))

stocks/views/user_routes.py
"""This module contains routes related to users in a Flask application."""
from flask import render_template, Blueprint, redirect, request, url_for, flash
import requests
from requests.exceptions import JSONDecodeError

user_bp = Blueprint('users', __name__, url_prefix='/users')
BASE_URL = 'http://localhost:5000/api/users'
headers = {'Content-Type': 'application/json'}



@user_bp.route('', methods=['GET'])
def list_users():
    """
    Retrieves a list of all users from the API and renders them in a template.
    """
    try:
        response = requests.get(BASE_URL, timeout=5).json()
        return render_template('users.html', users=response)
    except JSONDecodeError:
        return render_template('users.html')


@user_bp.route('/<int:user_id>', methods=['GET'])
def get_user(user_id: int):
    """
    Retrieves a user by ID from the API.
    """
    response = requests.get(BASE_URL + f'/{user_id}', timeout=5).json()
    return response



@user_bp.route('', methods=['POST'])
def create_user():
    """
    Creates a new user with the provided data and redirects to the user list.
    """
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    phone = request.form.get('phone')
    data = {'first_name': first_name, 'last_name': last_name, 'phone': phone}
    response = requests.post(BASE_URL, headers=headers, json=data, timeout=5).json()
    if response is False:
        flash('This phone number is already in use.')
    else:
        flash(f'User {first_name} {last_name} added successfully.', 'success')
    return redirect(url_for('users.list_users'))



@user_bp.route('/<int:user_id>', methods=['GET', 'POST'])
def update_user(user_id: int):
    """
    Updates a user with the provided data and redirects to the user list.
    """
    if request.method == 'POST':
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        phone = request.form.get('phone')
        data = {'first_name': first_name, 'last_name': last_name, 'phone': phone}
        response = requests.put(BASE_URL + f'/{user_id}', headers=headers, json=data, timeout=5).json()
        if response is False:
            flash('This phone number is already in use.')
        else:
            flash(f'User {first_name} {last_name} updated successfully.', 'success')
        return redirect(url_for('users.list_users'))



@user_bp.route('/<int:user_id>', methods=['DELETE'])
def delete_user(user_id: int):
    """
    Deletes a user by ID and redirects to the user list.
    """
    requests.delete(BASE_URL + f'/{user_id}', timeout=5)
    flash('User deleted successfully.', 'success')
    return redirect(url_for('users.list_users'))

stocks/views/users_stocks_routes.py
"""This module contains routes related to users_stocks in a Flask application."""
from flask import render_template, Blueprint, redirect, request, url_for, flash
import requests

user_stock_bp = Blueprint('users_stocks', __name__, url_prefix='/users/stocks')
BASE_URL = 'http://localhost:5000/api/users/stocks'                                     #users_stocks
headers = {'Content-Type': 'application/json'}


@user_stock_bp.route('/<int:user_id>', methods=['GET'])
def list_user_stocks(user_id: int):
    """
    Retrieve a list of user's stocks.
    """
    try:
        response = requests.get(BASE_URL + f'/{user_id}', timeout=5).json()
        stocks = requests.get('http://localhost:5000/api/stocks', timeout=5).json()
        return render_template('user.html', user_stocks=response, user_id=user_id, stocks=stocks)
    except TypeError:
        return render_template('user.html', response=[], user_id=user_id, stocks=stocks)


@user_stock_bp.route('/<int:user_id>', methods=['POST'])
def buy_stock(user_id: int):
    """
    Buy stocks for a user.
    """
    company = request.form.get('company')
    stocks_amount = request.form.get('stocks_amount')
    data = {'company': company, 'stocks_amount': int(stocks_amount)}
    response = requests.post(BASE_URL + f'/{user_id}', headers=headers, json=data, timeout=5).json()
    if response == {'message': 'Too many stocks to buy.'}:
        flash('Too many stocks to buy.')
    elif response is None:
        flash("There are no company with this name.")
    elif response is False:
        flash("There are no company with this name.")
    else:
        flash('Successfully bought')
    return redirect(url_for('users_stocks.list_user_stocks', user_id=user_id))


@user_stock_bp.route('/<int:user_id>/<int:stock_id>', methods=['GET'])
def get_stock(user_id: int, stock_id: int):
    """
    Retrieve details of a user's specific stock.
    """
    response = requests.get(BASE_URL + f'/{user_id}/{stock_id}', timeout=5).json()
    return response


@user_stock_bp.route('/<int:user_id>/<int:stock_id>/<int:user_stock_id>', methods=['DELETE'])
def delete_stock(user_id: int, stock_id: int, user_stock_id: int):
    """
    Delete a user's specific stock.
    """
    requests.delete(BASE_URL + f'/{user_id}/{stock_id}/{user_stock_id}', timeout=5)
    flash('Stock deleted successfully.', 'success')
    return redirect(url_for('users_stocks.list_user_stocks'))

stocks/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auction Home Page</title>
    <link rel="stylesheet" href="static/home.css">
</head>
<body>
<h1>Welcome to the "My Stocks" App</h1>
<p>
    Please select from the following options:
</p>
<ul>
    <li><a href="{{ url_for('users.list_users') }}">List of Users</a></li>
    <li><a href="{{ url_for('stocks.list_stocks') }}">List of Stocks</a></li>
</ul>
</body>
</html>

stocks/templates/stocks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stocks</title>
    <link href="static/index.css" rel="stylesheet" type="text/css">
</head>
<body>

<h1>List of Stocks</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissable" role="alert">
    {{message}}
    <button type="button" class="close" onclick="this.parentNode.style.display = 'none';">
        <span aria-hidden="true">X</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<form action="{{ url_for('stocks.list_stocks') }}" method="GET">
    <div class="Filtering">
      <label for="min_price">Minimum price:</label>
      <input type="number" id="min_price" name="min_price" class="form-control" min="0" step="0.01">
      <label for="max_price">Maximum price:</label>
      <input type="number" id="max_price" name="max_price" class="form-control" min="0" step="0.01">
      <input type="submit" value="Filter">
    </div>
 </form>
<button onclick="show1('block')" class="add">Add new Stock</button>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Company</th>
        <th>Sector</th>
        <th>Amount</th>
        <th>Price ($)</th>
        <th>Actions</th>
    </tr>
    </thead>
    {% for stock in stocks %}
    <tr>
        <td>{{ stock.id }}</td>
        <td>{{ stock.company }}</td>
        <td>{{ stock.sector }}</td>
        <td>{{ stock.amount }}</td>
        <td>{{ stock.price }}</td>
        <td>
            <button onclick="show2('block', {{stock.id}})" class="edit">Edit</button>
            <button onclick="deleteStock({{ stock.id }})" class="delete">Delete</button>
            </form>
            <div onclick="show2('none', {{stock.id}})" id="gray2-{{stock.id}}"></div>
            <div id="window2-{{stock.id}}">
                <div class="form">
                    <h2>Edit Stock</h2>
                    <form method="POST" action="{{ url_for('stocks.update_stock', stock_id=stock.id) }}">
                        <label for="amount">The entered number will only be added to the current
                            amount:</label><br><br>
                        <input type="number" name="amount" class="input" id="amount" placeholder="Add only" value="0">
                        <br>
                        <input type="number" name="price" class="input" id="price" value="{{ stock.price }}"
                               required step="0.01">
                        <button type="submit" class="save">Update</button>
                    </form>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>

<div id="gray1"></div>
<div id="window1-stock">
    <div class="form">
        <h2>Create Stock</h2>
        <form id="create-form" action="{{ url_for('stocks.create_stock') }}" method="POST">
            <input type="text" placeholder="Company" name="company" required class="input">
            <br>
            <input type="text" placeholder="Sector" name="sector" required class="input">
            <br>
            <input type="number" placeholder="Amount" name="amount" required min="100" class="input">
            <br>
            <input type="number" placeholder="Price" name="price" required min="10" step="0.01" class="input">
            <br>
            <input onclick="show1('none')" type="submit" value="Cancel" class="cancel">
            <input type="submit" value="Save" class="save">
        </form>
    </div>
</div>

<p><a href="{{ url_for('home') }}">Home</a></p>

<script>
    function show1(state)
    {
        document.getElementById('window1-stock').style.display = state;
        document.getElementById('gray1').style.display = state;
    }
    function show2(state, stockId)
    {
        document.getElementById('window2-' + stockId).style.display = state;
        document.getElementById('gray2-' + stockId).style.display = state;
    }
    function deleteStock(stockId) {
        if (confirm("Are you sure you want to delete stock " + stockId + "?")) {
            fetch("/stocks/" + stockId, {
                method: "DELETE"
            })
            .then(data => {
                // Reload the page to update the list of stocks
                location.reload();
            })
            .catch(error => console.error(error));
        }
    }

</script>
</body>
</html>

stocks/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Stocks</title>
    <link href="/static/index.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>My Stocks</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissable" role="alert">
    {{message}}
    <button type="button" class="close" onclick="this.parentNode.style.display = 'none';">
        <span aria-hidden="true">X</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<button onclick="show1('block')" class="add">Buy stocks</button>
<form action="{{ url_for('stocks.list_stocks') }}" method="GET">
    <div class="Filtering">
      <label for="min_price">Minimum suma:</label>
      <input type="number" id="min_price" name="min_price" class="form-control" min="0" step="0.01">
      <label for="max_price">Maximum suma:</label>
      <input type="number" id="max_price" name="max_price" class="form-control" min="0" step="0.01">
      <input type="submit" value="Filter">
    </div>
 </form>
<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Stock_id</th>
        <th>Company</th>
        <th>Stocks Amount</th>
        <th>Suma ($)</th>
        <th>Actions</th>
    </tr>
    </thead>
    {% for stock in user_stocks %}
    <tr>
        <td>{{ stock.id }}</td>
        <td>{{ stock.stock_id }}</td>
        <td>{{ stock.company }}</td>
        <td>{{ stock.stocks_amount }}</td>
        <td>{{ stock.suma }}</td>
        <td>
            <button onclick="deleteStock({{ stock.user_id }}, {{ stock.stock_id }}, {{ stock.id }})"
                    class="delete">Sell stocks</button>
        </td>
    {% endfor %}
</table>

<div id="gray1"></div>
<div id="window1">
    <div class="form">
        <h2>Make Stocks</h2>
        <form id="create-form" action="{{ url_for('users_stocks.buy_stock', user_id=user_id) }}" method="POST">
            <input list="companies" type="text" placeholder="Company" name="company" required class="input">
            <datalist id="companies">
                {% for stock in stocks %}
             <option value="{{ stock.company }}">
                {% endfor %}
            </datalist>
            <br>
            <input type="number" placeholder="Stocks amount" name="stocks_amount" required class="input">
            <br>
            <input onclick="show1('none')" type="submit" value="Cancel" class="cancel">
            <input type="submit" value="Save" class="save">
        </form>
    </div>
</div>


<p><a href="{{ url_for('users.list_users', user_id=user_id) }}">Previous page</a></p>

<script>
    function show1(state)
    {
        document.getElementById('window1').style.display = state;
        document.getElementById('gray1').style.display = state;
    }
    function deleteStock(userId, stockId, id) {
        if (confirm("Are you sure you want to sell stock " + id + "?")) {
            fetch("/users/stocks/" + userId + '/' + stockId + '/' + id, {
                method: "DELETE"
            })
            .then(data => {
                // Reload the page to update the list of stocks
                location.reload();
            })
            .catch(error => console.error(error));
        }
    }
</script>
</body>
</html>

stocks/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
    <link href="static/index.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>List of Users</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissable" role="alert">
    {{message}}
    <button type="button" class="close" onclick="this.parentNode.style.display = 'none';">
        <span aria-hidden="true">X</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<button onclick="show1('block')" class="add">Add new User</button>
<div class="Filtering">
    <form method="GET" action="{{ url_for('users.list_users') }}">
        <label for="start_date">Registration date from:</label>
        <input type="date" id="start_date" name="start_date">
        <label for="end_date">by:</label>
        <input type="date" id="end_date" name="end_date">
        <input type="submit" value="Filter">
    </form>
</div>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Stocks Amount</th>
        <th>Registration Date</th>
        <th>Phone</th>
        <th>Actions</th>
    </tr>
    </thead>
    {% for user in users %}
    <tr>
        <td>{{ user.id }}</td>
        <td><a class="link" href="{{ url_for('users_stocks.list_user_stocks', user_id=user.id) }}">{{
            user.first_name
            }}</a></td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.stocks_amount }}</td>
        <td>{{ user.registration_date }}</td>
        <td>{{ user.phone }}</td>
        <td>
            <button onclick="show2('block', {{user.id}})" class="edit">Edit</button>
            <button onclick="deleteUser({{ user.id }})" class="delete">Delete</button>
            <div onclick="show2('none', {{user.id}})" id="gray2-{{user.id}}"></div>
            <div id="window2-{{user.id}}">
                <div class="form">
                    <h2>Edit User</h2>
                    <form method="POST" action="{{ url_for('users.update_user', user_id=user.id) }}">
                        <input type="text" name="first_name" class="input" id="first_name"
                               value="{{ user.first_name }}"
                               required>
                        <br>
                        <input type="text" name="last_name" class="input" id="last_name" value="{{ user.last_name }}"
                               required>
                        <br>
                        <input type="tel" name="phone" class="input" id="phone" value="{{ user.phone }}" required>
                        <button type="submit" class="save">Update</button>
                    </form>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>

<div id="gray1"></div>
<div id="window1">
    <div class="form">
        <h2>Create User</h2>
        <form id="create-form" action="{{ url_for('users.create_user') }}" method="POST">
            <input type="text" placeholder="First name" name="first_name" required class="input">
            <br>
            <input type="text" placeholder="Last name" name="last_name" required class="input">
            <br>
            <input type="tel" placeholder="Phone" name="phone" required class="input">
            <br>
            <input onclick="show1('none')" type="submit" value="Cancel" class="cancel">
            <input type="submit" value="Save" class="save">
        </form>
    </div>
</div>

<p><a href="{{ url_for('home') }}">Home</a></p>

<script>
    function show1(state)
    {
        document.getElementById('window1').style.display = state;
        document.getElementById('gray1').style.display = state;
    }
    function show2(state, userId)
    {
        document.getElementById('window2-' + userId).style.display = state;
        document.getElementById('gray2-' + userId).style.display = state;
    }
    function deleteUser(userId) {
        if (confirm("Are you sure you want to delete user " + userId + "?")) {
            fetch("/users/" + userId, {
                method: "DELETE"
            })
            .then(data => {
                // Reload the page to update the list of users
                location.reload();
            })
            .catch(error => console.error(error));
        }
    }

</script>
</body>
</html>